eureka:
  client:
    register-with-eureka: false
server:
  port: 8090
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: c
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/buses/**
            - Path=/api/v1/amenities/**
